#!/bin/bash

# Copyright (c) 2017 Matt Champion
# Licensed under the MIT licence

# This hook is called with the two parameters:
#
# - name of the remote being pushed to
# - URL of the remote being pushed to
#
# Information about the commits to be pushed is passed
# through the standard input. A single line is provided for
# each ref being pushed:
#
# <local ref> <local sha1> <remote ref> <remote sha1>

remote="$1"
url="$2"

IFS=' '
while read local_ref local_sha remote_ref remote_sha ; do
    # For each remote list the commits that are present locally
    # but not in the remote
    while read commit ; do
        # For each commit check if the message contains 'fixup'
        # and if it does prevent pushing the commit
        git log --format=%B -n 1 ${commit} | grep -i fixup >> /dev/null
        if [ $? -eq 0 ]; then
            echo "${commit} rejected, needs to be fixed up"
            git log --format=%B -n 1 ${commit} | cat
            echo "Alternatively use the flag --no-verify to disable the verification."
            exit 1
        fi
    done < <(git log --format=%H ${remote_sha}..${local_sha})
done

exit 0
